In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('final_dataset.csv')
df.head()

   density_per_km   latitude  longitude  ...  year  month  cases
0    12625.800781 -34.603684 -58.381559  ...  2016      3      2
1    12625.800781 -34.603684 -58.381559  ...  2016      3      0
2    12625.800781 -34.603684 -58.381559  ...  2016      3      1
3    12625.800781 -34.603684 -58.381559  ...  2016      3      0
4    12625.800781 -34.603684 -58.381559  ...  2016      4      0

[5 rows x 25 columns]

In [ ]:
df.shape

(174103, 25)

In [ ]:
# Remove duplicate rows
df = df.drop_duplicates(keep='first', inplace=False)

In [ ]:
df.shape

(103045, 25)

In [ ]:
feature_scale = [feature for feature in df.columns if feature in ['density_per_km','precipMM']]

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
scaler.fit(df[feature_scale])

MinMaxScaler(copy=True, feature_range=(0, 1))

In [ ]:
data = pd.concat([df[['cases','latitude', 'longitude', 'maxtempC', 'mintempC',
       'totalSnow_cm', 'sunHour', 'uvIndex', 'moon_illumination', 'DewPointC',
       'FeelsLikeC', 'HeatIndexC', 'WindChillC', 'WindGustKmph', 'cloudcover',
       'humidity', 'pressure', 'tempC', 'visibility',
       'winddirDegree', 'windspeedKmph', 'year', 'month']].reset_index(drop=True),
                    pd.DataFrame(scaler.transform(df[feature_scale]), columns=feature_scale)],axis=1)

data.head()

   cases   latitude  longitude  maxtempC  ...  year  month  density_per_km  precipMM
0      2 -34.603684 -58.381559        24  ...  2016      3        0.505636       0.0
1      0 -34.603684 -58.381559        24  ...  2016      3        0.505636       0.0
2      1 -34.603684 -58.381559        24  ...  2016      3        0.505636       0.0
3      0 -34.603684 -58.381559        22  ...  2016      4        0.505636       0.0
4      1 -34.603684 -58.381559        22  ...  2016      4        0.505636       0.0

[5 rows x 25 columns]

In [ ]:
data.isnull().sum()

cases                0
latitude             0
longitude            0
maxtempC             0
mintempC             0
totalSnow_cm         0
sunHour              0
uvIndex              0
moon_illumination    0
DewPointC            0
FeelsLikeC           0
HeatIndexC           0
WindChillC           0
WindGustKmph         0
cloudcover           0
humidity             0
pressure             0
tempC                0
visibility           0
winddirDegree        0
windspeedKmph        0
year                 0
month                0
density_per_km       0
precipMM             0
dtype: int64

In [ ]:
data.to_csv('regression_dataset.csv', index=False)

In [ ]:
datamod = pd.read_csv('regression_dataset.csv')

In [ ]:
datamod.head()

   cases   latitude  longitude  maxtempC  ...  year  month  density_per_km  precipMM
0      2 -34.603684 -58.381559        24  ...  2016      3        0.505636       0.0
1      0 -34.603684 -58.381559        24  ...  2016      3        0.505636       0.0
2      1 -34.603684 -58.381559        24  ...  2016      3        0.505636       0.0
3      0 -34.603684 -58.381559        22  ...  2016      4        0.505636       0.0
4      1 -34.603684 -58.381559        22  ...  2016      4        0.505636       0.0

[5 rows x 25 columns]